add authorization and registration
underwritter/weather-app pull request #2
Opened 2023-10-02 15:20 UTC by underwritter

1. добавлены возможности регистрации и авторизации, фронт и бэк.
2. исправлены ссылки в Header

2023-10-02 15:46 UTC, IvanOkoyanniy requested changes

2023-10-02 15:46 UTC, IvanOkoyanniy commented on client/src/components/header/header.tsx
> +          //TODO: Временно
актуально?

2023-10-02 15:46 UTC, IvanOkoyanniy commented on client/src/components/registration-page/registration-form.tsx
> +        email: data.email,
```
//email: data.email =>
const { email, password, name } = data;
const { success } = await registration({ email, password, name })
```

2023-10-02 16:14 UTC, cadzon approved these changes

2023-10-02 16:14 UTC, cadzon commented on client/src/components/custom-link/custom-link.tsx
> +    if (title === "Выйти") {
мне показался код странным потому что title это строка в интерфейсе CustomLinkProps

таким образом в ней может лежать любое значение, я бы рекомендовал изменить тип title в CustomLinkProps
на title: "Выйти" | "Jopa" | "Huy"

таким образом код может стать более очевидным, можно еще обработать этот случай каким то пропсом по типу isExit

2023-10-02 16:14 UTC, cadzon commented on client/src/components/custom_button/custom_button.tsx
> +      className={disabled ? "custom_button" : "disabled"}
класс disabled не очень универсален, таким образом если он будет применен к другому элементу может быть конфликт стилей 

disabled ? "custom-button" : "custom-button_disabled"

2023-10-02 16:14 UTC, cadzon commented on client/src/components/form-fields/input-field/input-field.tsx
> +          type={isShowPassword ? (type = "text") : (type = "password")}
(((((

2023-10-02 16:14 UTC, cadzon commented on client/src/components/form-fields/input-field/input-field.tsx
> +        <span className="span_error_message">
возможно если у нас нету ошибки нам нет необходимости рисовать этот div в дом дереве

2023-10-02 16:14 UTC, cadzon commented on client/src/components/form-fields/input-field/input-field.tsx
> +          {(errors[name]?.message as string) ?? ""}
код выглядит довольно универсально и дублируется в двух местах я бы вынес его в константу

2023-10-02 16:14 UTC, cadzon commented on client/src/components/header/header.tsx
> +              key={Math.random()}
((((

2023-10-02 16:14 UTC, cadzon commented on client/src/components/registration-page/registration-form.tsx
> +      }).unwrap();
```suggestion
      const {success} = await registration(data).unwrap();
```

2023-10-02 16:14 UTC, cadzon commented on client/src/index.tsx
> +  <React.StrictMode>
зач нужен React.StrictMode?

2023-10-02 16:14 UTC, cadzon commented on client/src/store/slices/auth.slice.ts
> +      state.usedSpace = action.payload.usedSpace;
срабатывает только если у объектов одинаковый нейминг ключей
```suggestion
      Object.assign(state, action.payload)
```

2023-10-04 09:56 UTC, underwritter commented on client/src/components/header/header.tsx
> +          //TODO: Временно
готово

2023-10-04 10:02 UTC, underwritter commented on client/src/components/registration-page/registration-form.tsx
> +        email: data.email,
готово, деструктуризация не нужна 
const {success} = await registration(data).unwrap();

2023-10-04 10:06 UTC, underwritter commented on client/src/api-action/user.js
> +      "http://localhost:5000/api/auth/registration",
файл и папка удалены, для запросов используется redux toolkit

2023-10-04 10:30 UTC, underwritter commented on client/src/components/app-router/app-router.tsx
> +  const isAuth = localStorage.getItem("success");
готово

2023-10-04 10:32 UTC, underwritter commented on client/src/components/app-router/app-router.tsx
> +          element={<div> Not Found or You do not have permission.</div>}
готово

2023-10-04 10:37 UTC, underwritter commented on client/src/components/form-fields/input-field/input-field.tsx
> +          {(errors[name]?.message as string) ?? ""}
+

2023-10-04 10:41 UTC, underwritter commented on client/src/components/header/header.tsx
> +              key={Math.random()}
+

2023-10-04 10:41 UTC, underwritter commented on client/src/components/header/header.tsx
> +              key={Math.random()}
проставлен индекс

2023-10-04 10:42 UTC, underwritter commented on client/src/components/registration-page/registration-form.tsx
> +      }).unwrap();
готово

2023-10-04 10:43 UTC, underwritter commented on client/src/index.tsx
> +  <React.StrictMode>
не нужен, исправлено

2023-10-04 10:46 UTC, underwritter commented on client/src/store/slices/auth.slice.ts
> +      state.usedSpace = action.payload.usedSpace;
работает !

2023-10-04 16:15 UTC, IvanOkoyanniy approved these changes

2023-10-05 13:43 UTC, underwritter commented on client/src/components/app-router/app-router.tsx
> +    if (isAuth && location.pathname === Path.Auth) {
хук useAuth есть, но именно в этом конкретном случае он не подходит для обновления компонента.

2023-10-05 13:43 UTC, underwritter commented on client/src/components/auth-page/auth-form.schema.ts
> +    .email("Введите действующую почту")
готово

2023-10-05 15:52 UTC, merged